[theme]

# Primary accent for interactive elements
primaryColor = 'purple'

# Background color for the main content area
backgroundColor = 'purple'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = 'purple'

# Color used for almost all text
textColor = 'purple'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
